### ISSUE TITLE
'module' object has no attribute 'imread

### ISSUE THREAD

**Issue by iairose** [XHUJOY/CycleGAN-tensorflow#11]
discriminatorA/d_h3_conv/Conv/weights:0
discriminatorA/d_bn3/scale:0
discriminatorA/d_bn3/offset:0
discriminatorA/d_h3_pred/Conv/weights:0
 [*] Reading checkpoint...
 [!] Load failed...
Processing image: ./datasets/horse2zebra/testA/n02381460_530.jpg
Traceback (most recent call last):
  File "main.py", line 55, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 52, in main
    else model.test(args)
  File "/root/CycleGAN-tensorflow/model.py", line 254, in test
    sample_image = [load_test_data(sample_file)]
  File "/root/CycleGAN-tensorflow/utils.py", line 41, in load_test_data
    img = imread(image_path)
  File "/root/CycleGAN-tensorflow/utils.py", line 93, in imread
    return scipy.misc.imread(path, mode='RGB').astype(np.float)
AttributeError: 'module' object has no attribute 'imread

**Comment by XHUJOY** [comment]
hi,
scipy.misc.imread is a standard function of scipy and you can find more details from here https://docs.scipy.org/doc/scipy-0.19.0/reference/generated/scipy.misc.imread.html
